spring:
  cloud:
    gateway:
      routes:
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            - name: SampleCookie
              args:
                message: My custom message for products
                name: user
                value: Felipe
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
